apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: veli-svc-deploy
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: veli-svc
    spec:
      containers:
      - name: veli-svc
        image: vgebrev/veli-svc:0.3
        ports:
        - containerPort: 3000