apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-veli-svc
spec:
  replicas: 1
  selector:
    app: veli-svc
  template:
    metadata:
      name: veli-svc
      labels:
        app: veli-svc
    spec:
      containers:
      - name: veli-svc
        image: vgebrev/veli-svc:0.2
        ports:
        - containerPort: 3000